name: Release

on:
  push:
    branches:
      - main

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.54.0

      - name: Build Linux x64
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload Linux x64 Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases[0].upload_url }}
          asset_path: ./target/x86_64-unknown-linux-gnu/release/your_program
          asset_name: your_program-linux-x64
          asset_content_type: application/octet-stream

  build-linux-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.54.0

      - name: Build Linux ARM
        run: cargo build --release --target arm-unknown-linux-gnu

      - name: Upload Linux ARM Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases[0].upload_url }}
          asset_path: ./target/arm-unknown-linux-gnu/release/your_program
          asset_name: your_program-linux-arm
          asset_content_type: application/octet-stream

  build-windows-x86:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.54.0

      - name: Build Windows x86
        run: cargo build --release --target i686-pc-windows-msvc

      - name: Upload Windows x86 Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases[0].upload_url }}
          asset_path: ./target/i686-pc-windows-msvc/release/your_program.exe
          asset_name: your_program-windows-x86.exe
          asset_content_type: application/octet-stream

  build-windows-x64:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.54.0

      - name: Build Windows x64
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload Windows x64 Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases[0].upload_url }}
          asset_path: ./target/x86_64-pc-windows-msvc/release/your_program.exe
          asset_name: your_program-windows-x64.exe
          asset_content_type: application/octet-stream
